global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ShareUpTime Services
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'post-service'
    static_configs:
      - targets: ['post-service:3003']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'feed-service'
    static_configs:
      - targets: ['feed-service:3004']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'media-service'
    static_configs:
      - targets: ['media-service:3005']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:3006']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Infrastructure Services
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 60s

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    scrape_interval: 60s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 60s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    scrape_interval: 60s

  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    scrape_interval: 60s
